name: tests
env: 
  SYSTEM_FILE: package-test.asd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux-macos:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, windows-latest]
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v3
          
      - name: Grant All Perms to Make Cache Restoring Possible
        run: |
          sudo mkdir -p /usr/local/etc/roswell
          sudo chown "${USER}" /usr/local/etc/roswell
          # Here the ros binary will be restored:
          sudo chown "${USER}" /usr/local/bin
      - name: Get Current Month
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache Roswell Setup
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-roswell
        with:
          path: |
            /usr/local/bin/ros
            ~/.cache/common-lisp/
            ~/.roswell
            /usr/local/etc/roswell
            .qlot
          key: "key-${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}-${{ matrix.lisp }}-${{ matrix.os }}-${{ hashFiles('qlfile.lock') }}"
      - name: Restore Path To Cached Files
        run: |
          echo $HOME/.roswell/bin >> $GITHUB_PATH
          echo .qlot/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'
      - uses: 40ants/setup-lisp@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with: 
          asdf-system: cl-info
      - name: Install Rove 
        run: ros install rove
      - name: Run tests
        working-directory: .
        run: |
          rove ${{ env.SYSTEM_FILE }}
