name: tests
env: 
  SYSTEM_FILE: package-test.asd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux-macos:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        lisp: 
          - sbcl-bin
          - ccl-bin
          - ecl
          - abcl-bin
        os: 
          - ubuntu-latest
          - macos-latest
          #- windows-latest
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v3
      - name: Grant All Perms to Make Cache Restoring Possible
        run: |
          sudo mkdir -p /usr/local/etc/roswell
          sudo chown "${USER}" /usr/local/etc/roswell
          # Here the ros binary will be restored:
          sudo chown "${USER}" /usr/local/bin
      - name: Get Current Month
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache Roswell Setup
        if: runner.os != 'macOS'
        id: cache
        uses: actions/cache@v3.0.2
        env:
          cache-name: cache-roswell
        with:
          path: |
            /usr/local/bin/ros
            ~/.cache/common-lisp/
            ~/.roswell
            /usr/local/etc/roswell
            .qlot
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.lisp }}-${{ hashFiles('qlfile.lock') }}"
      - name: Restore Path To Cached Files
        run: |
          echo $HOME/.roswell/bin >> $GITHUB_PATH
          echo .qlot/bin >> $GITHUB_PATH
          echo /usr/local/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'
      - uses: 40ants/setup-lisp@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          asdf-system: package-test
      - uses: 40ants/run-tests@v2.1.2
        with:
          asdf-system: package-test     
      
#      - name: Set Path To Cached Files
#        run: |
#          echo $HOME/.roswell/bin >> $GITHUB_PATH
#          echo /usr/local/bin >> $GITHUB_PATH
#        if: steps.cache.outputs.cache-hit == 'true'
#      - name: Install Homebrew 
#        if: runner.os == 'Linux'
#        env:
#          NONINTERACTIVE: 1
#        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#      - name: Install Roswell
#        if: steps.cache.outputs.cache-hit != 'true'
#        env:
#          LISP: ${{ matrix.lisp }}
#          ROSWELL_INSTALL_DIR: /home/runner/.local
#        run: |
#          brew install roswell
#          echo $HOME/.roswell/bin >> $GITHUB_PATH
#          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
#      - name: Install CCL
#        if: ${{ matrix.lisp }} == 'ccl-bin'
#        run: |
#          ros install ccl-bin 
#          ros use ccl-bin
#      - name: Install ECL
#        if: ${{ matrix.lisp }} == 'ecl'
#        run: |
#          ros install ecl
#          ros use ecl
#      - name: Install Rove 
#        run: ros install rove
#      - name: Run tests
#        working-directory: .
#        run: |
#          rove ${{ env.SYSTEM_FILE }}
