name: tests
env: 
  SYSTEM_FILE: package-test.asd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux-macos:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin, ecl, abcl-bin]
        os: [ubuntu-latest, macOS-latest]
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v2
        with: 
          asdf-system: cl-info
      - name: Install Rove 
        run: ros install rove
      - name: Run tests
      - run: |
          rove ${{ env.SYSTEM_FILE }}

